--[[ Uncomment the Demo you'd like to run! ]]--
			--require 'speed'
			--require 'engine'
			--require 'action'
			--require 'simple'
			--require 'event'
			--require 'stringGen'
			--require 'display'
